language: ruby
rvm:
- 2.2

#cache: bundler

# sudo: required
# sudo false tells travis to use docker containers
sudo: false

script:
 - chmod +x ./script/cibuild
 - ./script/cibuild

after_success:
 - chmod +x ./script/deploy
 - ./script/deploy

addons:
  apt:
    packages:
    - ncftp

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer